### ISSUE TITLE
enumerize ... multiple: true returns empty Enumerize::Set

### ISSUE THREAD

**Issue by akirill0v** [brainspec/enumerize#116]
When I bring class to the superclass with "becomes" it breaks enumeraize fields.
For multiple: true only:

``` ruby
class User < ActiveRecord::Base
  extend Enumerize
  enumerize :sex, :in => [:male, :female]
  serialize :interests, Array
  enumerize :interests, :in => [:music, :sports, :dancing, :programming], :multiple => true
end

class UniqStatusUser < User
end

uniq_user = UniqStatusUser.new
uniq_user.interests = [:sports, :dancing]
uniq_user.sex = :male
uniq_user.save!

user = uniq_user.becomes(User)
user.interests.must_equal uniq_user.interests # => <Enumerize::Set {}>
user.sex.must_equal uniq_user.sex # => "male"
```

**Comment by fernandodev** [comment]
Hi, 

I'm using version 0.11.0 and it occurs

```ruby
class Message < ActiveRecord::Base
  extend Enumerize

  serialize :devices, Array
  enumerize :devices, in: [:ios, :android], multiple: true

end
```

after I try to save, devices values won't be saved.

```ruby
m = Message.new(devices: [:ios, :android])
m.save!
```

**Comment by lest** [comment]
@fernandodev I cannot reproduce this issue in tests. I added the test 3cb333526c49a65badd671a1f1638b5f731eb6cb to make sure everything works as expected. Can you please push a test application reproducing it and open a separate issue?

**Comment by fernandodev** [comment]
@lest I finally found the error. It was a bad migration generation.

I fixed when I saw the [test](https://github.com/brainspec/enumerize/blob/master/test/activerecord_test.rb#L17)

**Comment by ibnukamy** [comment]
I'm still having this problem related to this.

```
  enumerize :role, in: [:admin, :trainer, :company], predicates: true, multiple: true, default: :company
```

after initialization, I can see the role field has `:company` value. But after created, the field becomes empty returning `=> <Enumerize::Set {}>`
