### ISSUE TITLE
Need new version for rails 6.1 

### ISSUE THREAD

**Issue by jicheng1014** [brainspec/enumerize#368]
The latest version 2.3.1 raise the exception: 

`ArgumentError (wrong number of arguments (given 2, expected 1))`

relative codes in gem: 

```ruby
               decorate_attribute_type(name, :enumerize) do |subtype|
                 Type.new(enumerized_attributes[name], subtype)
               end
```

Pull request #365 resolved this problem, but gem version forgot to change.

could you upgrade the gem and push it to rubygems?  

thx

**Comment by jesperronn** [comment]
Thanks for raising this issue. I had the exact same issue. 

Maintainers, can you craft a release?

Please reach out if you need any help 💪

**Comment by nashby** [comment]
@jesperronn @jicheng1014 hey! I just pushed a new version to Rubygems! Please give it a try.

**Comment by jesperronn** [comment]
Thanks. Will give it a try👍👍

**Comment by Isaius** [comment]
@nashby IDK if you forgot to update the latest release tag... but the repository is saying that still on `2.3.1`
